import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import mongoose from 'mongoose';
import User from '../models/User.js';
import { recordAudit } from './auditController.js';
import { DEMO_USERS, findDemoUser } from '../config/demoUsers.js';
import { recordLoginEvent } from '../config/loginActivity.js';
const sign = (id, extra = {}) => jwt.sign({ id, ...extra }, process.env.JWT_SECRET || 'development-only-secret', { expiresIn: process.env.JWT_EXPIRES_IN || '8h' });
const safe = user => ({ id: user._id, name: user.name, email: user.email, role: user.role, specialty: user.specialty });
const demoResetTokens = new Map();
const demoOtpCodes = new Map();
export async function register(req, res, next) { try { const { name, email, password, role = 'Patient' } = req.body; if (await User.exists({ email })) return res.status(409).json({ message: 'An account with that email already exists' }); const user = await User.create({ name, email, password: await bcrypt.hash(password, 12), role }); await recordAudit({ actor: user._id, action: 'REGISTER', resource: 'User', resourceId: user._id.toString(), req }); res.status(201).json({ token: sign(user._id), user: safe(user) }); } catch (e) { next(e); } }
export async function login(req, res, next) { try { const { email, password } = req.body; if (mongoose.connection.readyState !== 1) { const demo = findDemoUser(email); if (!demo || !(await bcrypt.compare(password, demo.password))) { recordLoginEvent({ email: String(email).toLowerCase(), name: demo?.name || 'Unknown account', role: demo?.role || 'Unknown', status: 'Failed', ip: req.ip }); return res.status(401).json({ message: 'Email or password is incorrect' }); } recordLoginEvent({ email: demo.email, name: demo.name, role: demo.role, status: 'Success', ip: req.ip }); return res.json({ token: sign(demo._id, { demo: true }), user: safe(demo) }); } const user = await User.findOne({ email }).select('+password'); if (!user || (user.lockedUntil && user.lockedUntil > new Date()) || !(await bcrypt.compare(password, user.password))) { recordLoginEvent({ email: String(email).toLowerCase(), name: user?.name || 'Unknown account', role: user?.role || 'Unknown', status: 'Failed', ip: req.ip }); if (user) { user.failedLoginAttempts += 1; if (user.failedLoginAttempts >= 5) user.lockedUntil = new Date(Date.now() + 15 * 60 * 1000); await user.save(); } return res.status(401).json({ message: 'Email or password is incorrect' }); } user.failedLoginAttempts = 0; user.lockedUntil = undefined; user.lastLoginAt = new Date(); await user.save(); recordLoginEvent({ email: user.email, name: user.name, role: user.role, status: 'Success', ip: req.ip }); await recordAudit({ actor: user._id, action: 'LOGIN', resource: 'User', resourceId: user._id.toString(), req }); res.json({ token: sign(user._id), user: safe(user) }); } catch (e) { next(e); } }
export async function me(req, res) { res.json({ user: safe(req.user) }); }
export async function forgotPassword(req, res, next) { try { const response = { message: 'If an account exists for that email, password reset instructions have been prepared.' }; const rawToken = crypto.randomBytes(32).toString('hex'); if (mongoose.connection.readyState !== 1) { demoResetTokens.set(crypto.createHash('sha256').update(rawToken).digest('hex'), { expires: Date.now() + 15 * 60 * 1000 }); response.resetToken = rawToken; return res.json(response); } const user = await User.findOne({ email: req.body.email }).select('+passwordResetTokenHash +passwordResetExpires'); if (!user) return res.json(response); user.passwordResetTokenHash = crypto.createHash('sha256').update(rawToken).digest('hex'); user.passwordResetExpires = new Date(Date.now() + 15 * 60 * 1000); await user.save(); await recordAudit({ actor: user._id, action: 'PASSWORD_RESET_REQUESTED', resource: 'User', resourceId: user._id.toString(), req }); if (process.env.NODE_ENV !== 'production') response.resetToken = rawToken; res.json(response); } catch (e) { next(e); } }
export async function resetPassword(req, res, next) { try { const tokenHash = crypto.createHash('sha256').update(req.params.token).digest('hex'); if (mongoose.connection.readyState !== 1) { const demoToken = demoResetTokens.get(tokenHash); if (!demoToken || demoToken.expires < Date.now()) return res.status(400).json({ message: 'This reset link is invalid or has expired.' }); demoResetTokens.delete(tokenHash); return res.json({ message: 'Password updated. You can now sign in.' }); } const user = await User.findOne({ passwordResetTokenHash: tokenHash, passwordResetExpires: { $gt: new Date() } }).select('+password +passwordResetTokenHash +passwordResetExpires'); if (!user) return res.status(400).json({ message: 'This reset link is invalid or has expired.' }); user.password = await bcrypt.hash(req.body.password, 12); user.passwordResetTokenHash = undefined; user.passwordResetExpires = undefined; user.failedLoginAttempts = 0; user.lockedUntil = undefined; await user.save(); await recordAudit({ actor: user._id, action: 'PASSWORD_RESET_COMPLETED', resource: 'User', resourceId: user._id.toString(), req }); res.json({ message: 'Password updated. You can now sign in.' }); } catch (e) { next(e); } }
export async function requestOtp(req, res, next) { try { const otp = String(crypto.randomInt(100000, 1000000)); const response = { message: 'If an account exists for that email, a six-digit verification code has been prepared.' }; if (mongoose.connection.readyState !== 1) { demoOtpCodes.set(req.body.email, { hash: crypto.createHash('sha256').update(otp).digest('hex'), expires: Date.now() + 10 * 60 * 1000, attempts: 0 }); response.demoOtp = otp; return res.json(response); } const user = await User.findOne({ email: req.body.email }).select('+passwordResetOtpHash +passwordResetOtpExpires'); if (!user) return res.json(response); user.passwordResetOtpHash = crypto.createHash('sha256').update(otp).digest('hex'); user.passwordResetOtpExpires = new Date(Date.now() + 10 * 60 * 1000); await user.save(); if (process.env.NODE_ENV !== 'production') response.demoOtp = otp; res.json(response); } catch (e) { next(e); } }
export async function verifyOtp(req, res, next) { try { const { email, otp } = req.body; const otpHash = crypto.createHash('sha256').update(otp).digest('hex'); if (mongoose.connection.readyState !== 1) { const record = demoOtpCodes.get(email); if (!record || record.expires < Date.now() || record.attempts >= 5 || record.hash !== otpHash) { if (record) record.attempts += 1; return res.status(400).json({ message: 'The verification code is invalid or expired.' }); } demoOtpCodes.delete(email); const rawToken = crypto.randomBytes(32).toString('hex'); demoResetTokens.set(crypto.createHash('sha256').update(rawToken).digest('hex'), { expires: Date.now() + 15 * 60 * 1000 }); return res.json({ resetToken: rawToken }); } const user = await User.findOne({ email }).select('+passwordResetOtpHash +passwordResetOtpExpires'); if (!user || !user.passwordResetOtpHash || user.passwordResetOtpExpires < new Date() || user.passwordResetOtpHash !== otpHash) return res.status(400).json({ message: 'The verification code is invalid or expired.' }); user.passwordResetOtpHash = undefined; user.passwordResetOtpExpires = undefined; const rawToken = crypto.randomBytes(32).toString('hex'); user.passwordResetTokenHash = crypto.createHash('sha256').update(rawToken).digest('hex'); user.passwordResetExpires = new Date(Date.now() + 15 * 60 * 1000); await user.save(); res.json({ resetToken: rawToken }); } catch (e) { next(e); } }
